### ISSUE TITLE
How to use :path argument in MergeFile?

### ISSUE THREAD

**Issue by secret963** [grab/cocoapods-pod-merge#20]
absolute path is OK, but relative path gets an error:

Fetching podspec for `DTCoreText` from `/Users/xxxxx/Documents/projects/test/DependentPods/DTCoreText`
Fetching podspec for `DTRichTextEditor` from `DependentPods/DTRichTextEditor`
[!] No podspec found for `DTRichTextEditor` in `DependentPods/DTRichTextEditor`

I'm sure DTRichTextEditor folder contains a file named 'DTRichTextEditor.podspec'.

my MergeFile:

group 'MyLib'
    pod 'DTRichTextEditor', :path => 'DependentPods/DTRichTextEditor'
    pod 'DTCoreText', :path => '/Users/xxxxx/Documents/projects/test/DependentPods/DTCoreText'
end

So, what's the problem?

**Comment by biocross** [comment]
Hi @secret963, looks like this is a bug in the plugin that needs to be fixed, thanks for reporting!

To unblock yourself in the meantime, just prepend the relative path with a `../`, like `pod 'DTRichTextEditor', :path => '../DependentPods/DTRichTextEditor'`. 

This is because for each group, the pod install happens in a temporary directory (`./MergeCache`) that's one level deeper than the `MergeFile`

**Comment by secret963** [comment]
It works, Thanks!
