### ISSUE TITLE
warm launch stats

### ISSUE THREAD

**Issue by InderKumarRathore** [grab/cocoapods-pod-merge#3]
Would be nice to see warm launch stats, cold launches are not useful.

**Comment by biocross** [comment]
I think cold launch stats definitely are useful, considering that's what users experience if they open your app after opening a bunch of other apps, since your app would have been previously terminated and removed from memory. Also, iOS doesn't share dylibs across apps due to the sandbox, which means the frameworks associated with a specific app are reloaded by the dynamic linker on a fresh launch. 

This behaviour has definitely improved in iOS 13 with `dyld 3.0`, where caching for dynamic frameworks has been extended to 3rd party apps, and warm launched numbers should be comparable for merged / non-merged cocoapods. But the improvement from merging pods still holds for all users on older devices & iOS versions.

Also, the benchmarks posted [here](https://github.com/grab/cocoapods-pod-merge/blob/master/wiki/benchmarks.md) are done on the [example project](https://github.com/grab/cocoapods-pod-merge/tree/master/PodMergeExample) in this repository, so feel free to benchmark with your specific parameters :)

**Comment by InderKumarRathore** [comment]
Apple mentioned in their talk that we should not focus on cold launch.
Warm launch  is what user will face most of the time. And yes merging pods would definitely improve the loading time.

**Comment by biocross** [comment]
With iOS 13, I agree the user will face warm launches more often than before. 

As you mentioned, I'll try and add benchmarks for **warm launches** as well. If you run any benchmarks, please do share them here!
